-- return {
--   "stevearc/conform.nvim",
--   opts = function(_, opts)
--     -- Define custom formatter configuration
--     opts.formatters = opts.formatters or {}
--     opts.formatters.erb_format = {
--       command = "/opt/homebrew/bin/mise",
--       args = { "x", "--", "erb-format" },
--       -- If erb-format needs the filename as argument:
--       -- args = function(self, ctx)
--       --   return { "x", "--", "erb-format", ctx.filename }
--       -- end,
--     }
--
--     -- Make sure formatters_by_ft exists
--     opts.formatters_by_ft = opts.formatters_by_ft or {}
--
--     -- Add erb_format for eruby files
--     opts.formatters_by_ft.eruby = { "erb_format" }
--
--     return opts
--   end,
-- }
-- return {
--   "stevearc/conform.nvim",
--   opts = function(_, opts)
--     -- Define custom formatter configuration
--     opts.formatters = opts.formatters or {}
--
--     -- Completely replace the erb_format formatter definition
--     opts.formatters.erb_format = {
--       command = "/opt/homebrew/bin/mise",
--       args = { "x", "--", "erb-format" },
--       -- stdin = true,
--       -- cwd = vim.fn.getcwd(),
--       -- require_cwd = false,
--     }
--
--     -- Make sure formatters_by_ft exists
--     opts.formatters_by_ft = opts.formatters_by_ft or {}
--
--     -- Add erb_format for eruby files
--     opts.formatters_by_ft.eruby = { "erb_format" }
--
--     return opts
--   end,
-- }
-- return {
--   "stevearc/conform.nvim",
--   opts = function(_, opts)
--     -- Define custom formatter configuration
--     opts.formatters = opts.formatters or {}
--
--     -- Use mise exec to run erb-format
--     opts.formatters.erb_format = {
--       command = "/opt/homebrew/bin/mise",
--       args = { "exec", "ruby", "--", "erb-format" },
--       stdin = true,
--     }
--
--     -- Make sure formatters_by_ft exists
--     opts.formatters_by_ft = opts.formatters_by_ft or {}
--
--     -- Add erb_format for eruby files
--     opts.formatters_by_ft.eruby = { "erb_format" }
--
--     return opts
--   end,
-- }
return {
  "stevearc/conform.nvim",
  -- opts = function(_, opts)
  --   -- Define custom formatter configuration
  --   opts.formatters = opts.formatters or {}
  --
  --   -- Configure erb_lint properly
  --   opts.formatters.erb_lint = {
  --     command = "/opt/homebrew/bin/mise",
  --     args = function(self, ctx)
  --       return {
  --         "exec",
  --         "ruby",
  --         "--",
  --         "erb_lint",
  --         "--autocorrect",
  --         ctx.filename, -- Pass the actual filename
  --       }
  --     end,
  --     stdin = false, -- Important: ERB-Lint operates on files, not stdin
  --     cwd = vim.fn.getcwd(), -- Run in the project directory
  --     require_cwd = false,
  --   }
  --
  --   -- Make sure formatters_by_ft exists
  --   opts.formatters_by_ft = opts.formatters_by_ft or {}
  --
  --   -- Use erb_lint for eruby files
  --   opts.formatters_by_ft.eruby = { "erb_lint" }
  --
  --   return opts
  -- end,
}
